shell = "zsh"

[plugins.autosuggestions]
local = "@autosuggestions@"
use = ["zsh-autosuggestions.zsh"]

[plugins.history-substring-search]
local = "@history_substring_search@"
use = ["zsh-history-substring-search.zsh"]

[plugins.fast-syntax-highlighting]
local = "@fast_syntax_highlighting@"
use = ["fast-syntax-highlighting.plugin.zsh"]
